### ISSUE TITLE
System.config Error

### ISSUE THREAD

**Issue by nym** [jagonalez/aurelia-navigation-menu#1]
By including this:

`
import { NavigationMenu } from 'aurelia-navigation-menu';
`

I get the following error:

> 
> TypeError: System.config is not a function
>     at Object.eval (config.js?af18:1)
>     at eval (aurelia-navigation-menu:141)
>     at Object.aurelia-navigation-menu (app.bundle.js:5827)
>     at __webpack_require__ (app.bundle.js:20)
>     at WebpackLoader.eval (aurelia-loader-webpack.js?b873:176)
>     at step (aurelia-loader-webpack.js?b873:36)
>     at Object.eval [as next] (aurelia-loader-webpack.js?b873:17)
>     at eval (aurelia-loader-webpack.js?b873:11)
>     at new Promise (<anonymous>)
>     at __awaiter (aurelia-loader-webpack.js?b873:7)
> 

The sample app works fine.

**Comment by jagonalez** [comment]
There was an issue with package.json pointing to the wrong file.

**Comment by nym** [comment]
Verified. Thank you @jagonalez !
