### ISSUE TITLE
navModel.href undefined

### ISSUE THREAD

**Issue by nym** [jagonalez/aurelia-navigation-menu#2]
_Note: I don't have a code sample yet, as the problem is not showing up when I try to repro using the example code you provided._

I'm having an issue with implementing the navmenu with a larger codebase.

Third level items are showing up, but with the incorrect href. From debugging, it seems that where `nav.href` is set in `navigation-menu.js`, navModel.href is undefined. The hrefs are showing up like 'undefined/mynestedpath' instead of 'mysection/mynestedpath'

Note that I am not blocking activate for my app on this.navigationMenu.ensureMenu(), because that would prevent my app from fully loading.

I'm not sure what to do exactly- if you have time to reach out to me, I am on https://gitter.im/aurelia/Discuss

**Comment by ordinaryorange** [comment]
@nym Hit the same issue here too. The issue is the code around line 104 in navigation-menu.js. It is not recursive and needs to be.
@jagonalez here is my fix if you wan to patch it in ( ),

    .then(i => {
               let updateHref = (navigation) => {
                      navigation.forEach(nav =>{
                               nav.href = '${navModel.href}/${nav.href ? nav.href : nav.config.route}'
                               updateHref(nav,navigation)
                       }
               }
               navModel.navigation = i
               updateHref(navModel.navigation)
               return navModel;
             })
